### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by zdolny** [jr-consulting/kodilla-test-repository#1]
- [x] usun ten dziwnym folder `Projects` razem z zawartoscia - nie wiem o co chodzi, a chyba nie jest czescia repozytorium (po usunieciu go zakomituj i wypushuj te zmiane)
- [x] usun nieuzywany plik js
- [x] rozumiem Twoj zabieg z demonstracja grunta, ale poprosze Cie, zeby ten plik wynikowy css byl podpiety do projektu, zeby mozna od razu to przetestowac
- [x] zalacz tez przykladowy obrazek, ktory tez bedzie na stronie po przemieleniu przez grunta
- [x] w `package.json` usun z `dependencies` grunt-cli - nie jest to zaleznosc, bez ktorej Twoj projekt produkcyjnie nie ruszy
- [x] dobra praktyka jest, zeby nie wrzucac do repo katalogu `node_modules` - usun go, zakomituj i wypushuj zmiane, a nastepnie dodaj sobie lokalnie plik `.gitignore` (z kropka) i wpisz tam `node_modules/` - git bedzie ignorowal ten folder

**Comment by jr-consulting** [comment]
ad 1 Usuniete. Folder został po testach z pierwszego zadania dot. githuba, jak jeszcze nie znałem treści kolejnego zadania. 
ad 2. Usuniety.
ad 3. In progress.
ad 4. In progress
ad 5. O ile dobrze pamietam to się tam chyba znalazło z automatu w wyniku wykonania komendy: npm install grunt --save-dev. 
ad 6.  Usunięte /node_modules, dodany .gitignore z wyjatkami.

**Comment by jr-consulting** [comment]
ad 3. podpialem do tego zadania projekt 4.3, które przeszło jeszcze zadanie 6.2 (przeróbka na sassa).
ad 4. wszystkie trzy obrazki zalaczone z katalogu images/build po modyfikacji przez grunta

**Comment by zdolny** [comment]
dziala super, jeszcze jeden z punktow odznaczylem - do zrobienia i dodatkowo popraw wciecia dla lepszej czytelnosci: https://scr.hu/mLlYX2

**Comment by jr-consulting** [comment]
Wprowadziłem zmiany do obu plików. 
Mam nadzieję, że to o to chodziło z wcięciami.

**Comment by zdolny** [comment]
ujednolicilem wciecia zamieniajac na taby - zerknij jak wyglada u Ciebie lokalnie
